### ISSUE TITLE
Allow adding multiple voice samples for voice cloning

### ISSUE THREAD

**Issue by Dgarc359** [Jiangshan00001/pyttsx4#11]
**Is your feature request related to a problem? Please describe.**
The example code shows how to provide a sample `.wav` file for vocal cloning. Is it possible / necessary to add more voice samples to improve accuracy of vocal cloning? Either that, or some guidelines on how to best produce a vocal clone with a single sample

**Describe the solution you'd like**
```python
# when calling engine.setProperty() - allow multiple file paths to be passed
engine.setProperty('speaker_wav', ['./speaker_sample_1.wav', './speaker_sample_2.wav']
```

**Comment by Jiangshan00001** [comment]
i think it is not needed.
i added some example input and output of the wav file.
see the repo readme.md  extera features 2.
