### ISSUE TITLE
save_to_file does not work on mac os ventura python 3.11.2

### ISSUE THREAD

**Issue by tylerq23** [Jiangshan00001/pyttsx4#3]
**Describe the bug**
save_to_file does not do anything but exits succesfully

**To Reproduce**
Use following code: 

import pyttsx4
engine = pyttsx4.init()
engine.save_to_file('Hello World', 'test.mp3')
engine.runAndWait()

**Expected behavior**
a file named test.mp3 should be placed right next to the python file

**Desktop (please complete the following information):**
 - OS: Mac OS

**Additional context**
I can switch .mp3 to .wav and it then generates the file, however the wav file appears to be corrupted and wont play any sound, and media players claim the file is corrupted.

Thanks!

**Comment by joemama0s** [comment]
That worked! Thank you so much. I also confirmed mp3 does not work, but this is fine. WAV format works. 

Thank you!

**Comment by qiulang** [comment]
> BTW: this should only support wav format. mp3 will not work.

Why is that ?
