### ISSUE TITLE
Segfault on Apple Silicon macs since Ventura 13.3.1(a) update

### ISSUE THREAD

**Issue by kilrah** [Jiangshan00001/pyttsx4#5]
Reported here on pyttsx3 but also happens on pyttsx4, any chance you could have a look at this?

https://github.com/nateshmbhat/pyttsx3/issues/274

**Comment by Jiangshan00001** [comment]
i have check the error, and it seems the pyobjc version problem.

the problem happens when pyobjc version is 9.1.1.

pip install pyobjc==9.0.1 fix the problem.

try and see.

**Comment by kilrah** [comment]
Thanks will have a look!

**Comment by kilrah** [comment]
Seems fine both ways indeed!
