### ISSUE TITLE
Program to executing completely

### ISSUE THREAD

**Issue by anshtyagi0** [Jiangshan00001/pyttsx4#9]
I was making personal assistant for myself but faced an error.

```py
def listen():
    with sr.Microphone() as source:
        speak("Listening...")
        r.pause_threshold = 1  
        audio = r.listen(source)
    try:
        speak("Recognizing...")
        query = r.recognize_google(audio, language='en') 
        print(f"User: {query}\n")
        return query
    except sr.UnknownValueError:
        speak("Sorry, I didn't catch that. Can you please repeat?")
        return listen()
    except sr.RequestError:
        speak("Oops! Something went wrong. Please check your internet connection.")
        return None

def speak(text):
    engine.say(text)
    engine.runAndWait()

speak("Hello! How can I assist you today?")
query = listen()
if query:
    running = assistant_logic(query)
```

but my code is only saying "Hello! How can I assist you today?" after that it stops working but I want it to first say ""Hello! How can I assist you today?" and then start listening to user.

**Desktop (please complete the following information):**
 - OS: Ventura 13.4 (M1)

**Comment by Jiangshan00001** [comment]
i have no mac os to try.
but you can try this:
run:
```
python3 -q -X faulthandler
```
then,
paste all your code to the command line.

seee is there any error message in detail?

**Comment by anshtyagi0** [comment]
no

**Comment by anshtyagi0** [comment]
When I debugged my code I got this error:
-------------------------------------------------------------------------------
pydev debugger: CRITICAL WARNING: This version of python seems to be incorrectly compiled (internal generated filenames are not absolute)
pydev debugger: The debugger may still function, but it will work slower and may miss breakpoints.
pydev debugger: Related bug: http://bugs.python.org/issue1666807
-------------------------------------------------------------------------------
Connected to pydev debugger (build 213.6777.50)
pydev debugger: Unable to find real location for: <frozen codecs>
pydev debugger: Unable to find real location for: <frozen importlib._bootstrap>
pydev debugger: Unable to find real location for: <frozen importlib._bootstrap_external>
pydev debugger: Unable to find real location for: <string>
pydev debugger: Unable to find real location for: <frozen zipimport>
pydev debugger: Unable to find real location for: <frozen abc>
pydev debugger: Unable to find real location for: <frozen io>
pydev debugger: Unable to find real location for: <frozen _collections_abc>
pydev debugger: Unable to find real location for: <frozen posixpath>
pydev debugger: Unable to find real location for: <frozen os>
pydev debugger: Unable to find real location for: <frozen genericpath>

**Comment by Jiangshan00001** [comment]
i have changed the code of this repo to fix the issue.
could you pleause try when you have time?

**Comment by anshtyagi0** [comment]
@Jiangshan00001  have you published them to pip

**Comment by Jiangshan00001** [comment]
no, i have not published them to pip.
just the repo is updated.

**Comment by Jiangshan00001** [comment]
try this :
```
pip install pyttsx4  --upgrade
```
```
def speak(text):
    engine.say(text)
    engine.runAndWait()

speak("Hello! How can I assist you today?")
speak("Hello! i want to know, could you speak twice?")
speak("tell me something, so that i can try the speak function.")

```

**Comment by anshtyagi0** [comment]
@Jiangshan00001  No it is only speaking 
```py
speak("Hello! How can I assist you today?")
```

**Comment by Jiangshan00001** [comment]
could you debug the code, run it step by step, to see which line is the code running?

**Comment by Jiangshan00001** [comment]
https://github.com/nateshmbhat/pyttsx3/issues/279

Edit: just for reference, earlier i was using pyobjc v9.2. changing to 9.0.1 worked
